### ISSUE TITLE
Move to Composer and a couple other minor things.

### ISSUE THREAD

**Issue by n0nag0n** [myaghobi/F3-Benchmark#1]
Referencing this other pull request. https://github.com/f3-factory/F3com-data/pull/116

I would get rid of the second one of these (cause it's redundant)
![image](https://user-images.githubusercontent.com/2322095/95476915-0834bf00-0945-11eb-8539-9f8652af1ae0.png)

And also I noticed a misspelling in your method `$this->enhanceExcutionTime();` => `$this->enhanceExecutionTime();`

**Comment by myaaghubi** [comment]
Fixed with commit d7dce6cb026df0cf0cea55b9e7f8801dbe8bb465

**Comment by n0nag0n** [comment]
Awesome! Thanks
